### ISSUE TITLE
Unable to install Avni client application on emulator using run_app_prod on 3.39.2 branch.

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-client#1030]
**Describe the bug**
Unable to install Avni client application on emulator using run_app_prod on 3.39.2 branch.
run_app_prod runs successfully on 3.39 branch.
Issue might be caused due to recent commits related to fixing Signing key.

Error log:
`
ERROR:/Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/bb5e116dc2872199891502eafeaa17ad/transformed/classes/classes.dex: D8: Type io.invertase.firebase.analytics.BuildConfig is defined multiple times: /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/bb5e116dc2872199891502eafeaa17ad/transformed/classes/classes.dex, /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/78fcdc18f50f5098fed37a41a9504dfb/transformed/classes/classes.dex
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
Type io.invertase.firebase.analytics.BuildConfig is defined multiple times: /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/bb5e116dc2872199891502eafeaa17ad/transformed/classes/classes.dex, /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/78fcdc18f50f5098fed37a41a9504dfb/transformed/classes/classes.dex
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:151)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:138)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.merge(DexMergingTask.kt:863)
	at com.android.build.gradle.internal.tasks.DexMergingWorkAction.run(DexMergingTask.kt:809)
	at com.android.build.gradle.internal.profile.ProfileAwareWorkAction.execute(ProfileAwareWorkAction.kt:74)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:66)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.create(NoIsolationWorkerFactory.java:62)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:97)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.lambda$execute$0(NoIsolationWorkerFactory.java:62)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:59)
	at org.gradle.workers.internal.DefaultWorkerExecutor.lambda$submitWork$2(DefaultWorkerExecutor.java:206)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:214)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/bb5e116dc2872199891502eafeaa17ad/transformed/classes/classes.dex
	at Version.fakeStackEntry(Version_3.0.76.java:0)
	at com.android.tools.r8.utils.w.a(SourceFile:68)
	at com.android.tools.r8.utils.w.a(SourceFile:28)
	at com.android.tools.r8.utils.w.a(SourceFile:27)
	at com.android.tools.r8.utils.w.b(SourceFile:3)
	at com.android.tools.r8.D8.run(D8.java:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:136)
	... 33 more
Caused by: com.android.tools.r8.internal.b: Type io.invertase.firebase.analytics.BuildConfig is defined multiple times: /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/bb5e116dc2872199891502eafeaa17ad/transformed/classes/classes.dex, /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/78fcdc18f50f5098fed37a41a9504dfb/transformed/classes/classes.dex
	at com.android.tools.r8.internal.UA.a(SourceFile:14)
	at com.android.tools.r8.internal.UA.a(SourceFile:22)
	at com.android.tools.r8.internal.Fw.b(SourceFile:6)
	at com.android.tools.r8.internal.Fw.a(SourceFile:23)
	at com.android.tools.r8.internal.Fw.a(SourceFile:10)
	at java.base/java.util.concurrent.ConcurrentHashMap.merge(ConcurrentHashMap.java:2048)
	at com.android.tools.r8.internal.Fw.a(SourceFile:6)
	at com.android.tools.r8.graph.I0$c.f(SourceFile:3)
	at com.android.tools.r8.dex.a.a(SourceFile:94)
	at com.android.tools.r8.dex.a.a(SourceFile:23)
	at com.android.tools.r8.D8.a(D8.java:21)
	at com.android.tools.r8.D8.d(D8.java:11)
	at com.android.tools.r8.D8.b(D8.java:1)
	at com.android.tools.r8.utils.w.a(SourceFile:24)
	... 36 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeLibDexGenericDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingTaskDelegate
   > There was a failure while executing work items
      > A failure occurred while executing com.android.build.gradle.internal.tasks.DexMergingWorkAction
         > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
           Type io.invertase.firebase.analytics.BuildConfig is defined multiple times: /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/bb5e116dc2872199891502eafeaa17ad/transformed/classes/classes.dex, /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-firebase/analytics/android/build/.transforms/78fcdc18f50f5098fed37a41a9504dfb/transformed/classes/classes.dex
           Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s

    at makeError (/Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:174:9)
    at /Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-community/cli-platform-android/node_modules/execa/index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (/Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/himeshr/IdeaProjects/avni-client/packages/openchs-android/node_modules/react-native/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
make: *** [_run_app] Error 1
`

**Comment by vinayvenu** [comment]
Fix so this works when we merge these changes to master

**Comment by himeshr** [comment]
Run_app_prod works for me on 3.39.2 branch as well as 3.39 branch.
