### ISSUE TITLE
Handle voided question group form elements when rendering the form

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-client#1413]
Describe the bug
The app crashes when I am trying to complete the encounter of ANC.

env : staging
org : APF
user : maha@APF
version : 8.1
Issue not happening on prerelease

Note : Uploaded the database

Steps to reproduce :
1.Login to the app
2.Register the individual as gender female
3.Enroll in the pregnancy
4.Try to complete the ANC

Expected result : it should save the encounter
Actual result : App is getting crashed

Image reference :
<img width="457" alt="Screenshot 2024-05-28 at 3 49 32 PM" src="https://github.com/avniproject/avni-client/assets/127730126/3c705916-0558-493c-9bbb-7149a8dc1fe5">

Video reference : 

https://github.com/avniproject/avni-client/assets/127730126/c3942514-f89b-473e-bc1a-aed1cf720359

### AC:
- Issue was identified to be voided question group form elements not being ignored while running form element group rule. So ignore them to fix this.
- Fix it on DEA as well if not handled

**Comment by 1t5j0y** [comment]
Issue is due to voided question group form elements not being ignored while running form element group rule.
https://github.com/avniproject/avni-client/blob/72e0430b9731728c00ea3122bff4dcba1b3596d9/packages/openchs-android/src/service/RuleEvaluationService.js#L512

**Comment by AchalaBelokar** [comment]
- [ ] I login with maha@APF and try to sync it is giving me this error I just deleted only one element net from individual registration ..
undefined is not a function
at anonymous (address at index.android.bundle:1:874716)
at anonymous (address at index.android.bundle:1:711159)
at forEach (address at index.android.bundle:1:725997)
at deleteOutOfSyncDrafts (address at index.android.bundle:1:874650)
at fromResource (address at index.android.bundle:1:874493)
at anonymous (address at index.android.bundle:1:1581639)
at reduce ((native)::)
at persistAll (address at index.android.bundle:1:1588411)
at processResponse (address at index.android.bundle:1:1592321)
at anonymous (address at index.android.bundle:1:1592580)
at tryCallOne (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
at anonymous (/root/react-native/packages/react-native/ReactAndroid/hermes-engine/.cxx/MinSizeRel/1h352kp3/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
at apply ((native)::)
at anonymous (address at index.android.bundle:1:247177)
at _callTimer (address at index.android.bundle:1:246171)
at _callReactNativeMicrotasksPass (address at index.android.bundle:1:246336)
at callReactNativeMicrotasks (address at index.android.bundle:1:248258)
at __callReactNativeMicrotasks (address at index.android.bundle:1:98297)
at anonymous (address at index.android.bundle:1:97436)
at __guard (address at index.android.bundle:1:98174)
at flushedQueue (address at index.android.bundle:1:97347)
at invokeCallbackAndReturnFlushedQueue (address at index.android.bundle:1:97290)

**Comment by Dinesh2019** [comment]
Tested with scenario : (Mobile app and Web app )

- [ ] added the QG and tried to save the form.
- [ ] Remove the QG and tried to save the form.
- [ ] Added the QG with two different question and tried to save the form.
- [ ] Removed one question and tried to save the form.
