### ISSUE TITLE
Duplicate syncs creates duplicate rows in subject program eligibility thereby failing future syncs

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-client#945]
related ticket: https://avni.freshdesk.com/a/tickets/2550

Because of multiple syncs triggered at the same time, multiple subject program eligibility of same uuid is inserted into the db. This results in a case where user is unable to update the subject program eligibility since there are duplicates.

To do:
- add unique constraint around combination of uuid and organisation id on subject program eligibility table - so that the second duplicate sync 'll fail
- find similar tables where unique constraint was missed: one such case already dealt was https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/516

Out of scope:
- find the root cause for multiple syncs triggered at the same time: dealt in https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/511

**Duplicate subject program eligibility with nearby created times:**
```
1916,291,9a58766b-c4ae-4fac-9b17-3ce6c193ec6e,false,0,6641,6641,2023-04-06 06:57:47.286 +00:00,2023-04-06 06:57:47.286 +00:00,1314117,595,false,2023-04-06 05:58:50.000000 +00:00,{}

1917,291,9a58766b-c4ae-4fac-9b17-3ce6c193ec6e,false,0,6641,6641,2023-04-06 06:57:47.330 +00:00,2023-04-06 06:57:47.330 +00:00,1314117,595,false,2023-04-06 05:58:50.000000 +00:00,{}
```

**The above resulted in the below stacktrace when future syncing:**
```
2023-04-14 05:10:11.348  INFO 14228 --- [http-nio-8021-exec-22] .s.w.SubjectProgramEligibilityController : Saving SubjectProgramEligibility with uuid {9a58766b-c4ae-4fac-9b17-3ce6c193ec6e}
2023-04-14 05:10:11.354 ERROR 14228 --- [http-nio-8021-exec-22] org.avni.server.web.ErrorInterceptors    : query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2

org.springframework.dao.IncorrectResultSizeDataAccessException: query did not return a unique result: 2; nested exception is javax.persistence.NonUniqueResultException: query did not return a unique result: 2
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:379)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:227)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:507)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	

        at org.avni.server.common.EntityHelper.newOrExistingEntity(EntityHelper.java:19)
	at org.avni.server.common.EntityHelper.newOrExistingEntity(EntityHelper.java:13)
	at org.avni.server.web.AbstractController.newOrExistingEntity(AbstractController.java:11)
	at org.avni.server.web.SubjectProgramEligibilityController.save(SubjectProgramEligibilityController.java:84)
	at org.avni.server.web.SubjectProgramEligibilityController$$FastClassBySpringCGLIB$$54460fc0.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.avni.server.web.SubjectProgramEligibilityController$$EnhancerBySpringCGLIB$$3107b9ec.save(<generated>)
	
Caused by: javax.persistence.NonUniqueResultException: query did not return a unique result: 2
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:123)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1471)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:107)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:214)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:91)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:136)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:125)
	

2023-04-14 05:10:11.357  INFO 14228 --- [http-nio-8021-exec-22] o.a.s.f.security.AuthenticationFilter    : POST /subjectProgramEligibility?null User: umangk@power Organisation: PoWER Time: 11 ms
```

**Comment by himeshr** [comment]
Current openchs.public schema db tables structure is as seen in this dump file..
[Uploading... openchs_staging-2023_04_17_15_17_21-dump.sql]

**Comment by himeshr** [comment]
Unique Constraints analysis doc is available at https://docs.google.com/spreadsheets/d/1nrlh7lFFXA1K0UQtmgTLHCEGUQvJmOdlDg5Lk0uSwzY/edit?usp=sharing

We'll only be implementing those queries that are marked for release 3.38.1 as part of **this** card.

Addition of unique constraint around combination of "uuid" and "organisation id" on reference data tables will be done as part of https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-server/542

**Comment by himeshr** [comment]
While performing code review, please refer to all commits tagged #542 and #945 in branch 3.38 on avni-server repo
